# /etc/modules-load.d/docker.conf

# Filesystem
overlay

# Network
bridge
veth

# Netfilter modules
ip_tables
iptable_nat
iptable_filter
iptable_mangle

nf_nat
nf_conntrack
nf_defrag_ipv4
nf_tables

nft_chain_nat
nft_compat

xt_MASQUERADE
xt_REDIRECT
xt_addrtype
xt_conntrack
xt_mark
xt_multiport
xt_nat
xt_set
xt_state
xt_tcpudp
xt_LOG
